//! Raw FFI bindings to libx265.
//!
//! Generated by hand from x265.h (libx265 3.6).
//! Only the subset needed for encoding is bound; the analysis-reuse,
//! VMAF, dolby-vision and zone fields are omitted from x265_param since
//! we never touch them and their absence does not affect ABI on the fields
//! we *do* use (we always call x265_param_default() first and set values
//! via x265_param_parse(), never by direct field access).

#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals, dead_code)]

use std::ffi::{c_char, c_double, c_int, c_void};

// ─── opaque types ────────────────────────────────────────────────────────────

#[repr(C)]
pub struct x265_encoder {
    _private: [u8; 0],
}

#[repr(C)]
pub struct x265_picyuv {
    _private: [u8; 0],
}

// ─── NAL unit ────────────────────────────────────────────────────────────────

#[repr(C)]
pub struct x265_nal {
    /// NalUnitType
    pub type_:     u32,
    /// size of payload in bytes
    pub sizeBytes: u32,
    /// pointer to NAL payload (valid until next call to x265_encoder_encode)
    pub payload:   *mut u8,
}

// ─── picture ─────────────────────────────────────────────────────────────────

/// We only declare the fields we actually read/write.
/// x265_picture is not opaque — caller allocates it — but we access all
/// fields via x265_picture_init() + direct field writes, which is safe
/// as long as the struct size matches. We use x265_picture_alloc() so
/// libx265 allocates the memory with the correct size for the compiled
/// library version.
#[repr(C)]
pub struct x265_picture {
    pub pts:        i64,
    pub dts:        i64,
    pub userData:   *mut c_void,
    pub planes:     [*mut c_void; 3],
    pub stride:     [c_int; 3],
    pub bitDepth:   c_int,
    pub sliceType:  c_int,
    pub poc:        c_int,
    pub colorSpace: c_int,
    // remaining fields omitted — always call x265_picture_alloc()
    // and never dereference past colorSpace in our code
    _pad: [u8; 4096],
}

// ─── colour space constants ───────────────────────────────────────────────────

pub const X265_CSP_I420: c_int = 1;
pub const X265_CSP_I422: c_int = 2;
pub const X265_CSP_I444: c_int = 3;

// ─── rate-control modes ───────────────────────────────────────────────────────

pub const X265_RC_ABR: c_int = 0;
pub const X265_RC_CQP: c_int = 1;
pub const X265_RC_CRF: c_int = 2;

// ─── slice type constants ─────────────────────────────────────────────────────

pub const X265_TYPE_AUTO: c_int = 0x0000;
pub const X265_TYPE_IDR:  c_int = 0x0001;
pub const X265_TYPE_I:    c_int = 0x0002;
pub const X265_TYPE_P:    c_int = 0x0003;
pub const X265_TYPE_B:    c_int = 0x0005;

// ─── param ───────────────────────────────────────────────────────────────────

/// x265_param is treated as opaque: always allocate with x265_param_alloc()
/// and set values with x265_param_parse(). We never dereference this struct
/// from Rust, so we only need the opaque pointer.
#[repr(C)]
pub struct x265_param {
    _private: [u8; 0],
}

// ─── extern functions ─────────────────────────────────────────────────────────

#[cfg_attr(windows, link(name = "x265-static"))]
#[cfg_attr(not(windows), link(name = "x265"))]
extern "C" {
    // ── param ────────────────────────────────────────────────────────────────

    /// Allocate an x265_param on the heap (correct size for this build).
    pub fn x265_param_alloc() -> *mut x265_param;

    /// Free a heap-allocated x265_param.
    pub fn x265_param_free(param: *mut x265_param);

    /// Fill param with defaults.
    pub fn x265_param_default(param: *mut x265_param);

    /// Set a single named parameter.
    /// Returns 0 on success, X265_PARAM_BAD_NAME or X265_PARAM_BAD_VALUE on error.
    pub fn x265_param_parse(
        param: *mut x265_param,
        name:  *const c_char,
        value: *const c_char,
    ) -> c_int;

    /// Apply a named profile ("main", "main10", …).
    /// Returns 0 on success, negative on failure.
    pub fn x265_param_apply_profile(
        param:   *mut x265_param,
        profile: *const c_char,
    ) -> c_int;

    /// Apply a named preset + optional tune.
    /// preset: "ultrafast" … "placebo"
    /// tune:   "psnr" | "ssim" | "grain" | "zerolatency" | NULL
    pub fn x265_param_default_preset(
        param:  *mut x265_param,
        preset: *const c_char,
        tune:   *const c_char,
    ) -> c_int;

    // ── picture ───────────────────────────────────────────────────────────────

    /// Allocate an x265_picture on the heap.
    pub fn x265_picture_alloc() -> *mut x265_picture;

    /// Free a heap-allocated x265_picture.
    pub fn x265_picture_free(pic: *mut x265_picture);

    /// Initialise all fields to defaults (bitDepth, colorSpace, sliceType=auto).
    pub fn x265_picture_init(param: *mut x265_param, pic: *mut x265_picture);

    // ── encoder ───────────────────────────────────────────────────────────────

    // NOTE: x265_encoder_open is declared further down as a Rust wrapper,
    // not here. Modern libx265 exports it only under a version-suffixed
    // symbol name (e.g. x265_encoder_open_215) via a C preprocessor glue
    // macro in x265.h — linking against the bare, unversioned name fails
    // with "undefined reference". See the wrapper below.

    /// Write SPS/PPS/VPS headers into *pp_nal.
    /// Returns total byte size of payload, negative on error.
    pub fn x265_encoder_headers(
        encoder: *mut x265_encoder,
        pp_nal:  *mut *mut x265_nal,
        pi_nal:  *mut u32,
    ) -> c_int;

    /// Encode one picture.
    /// Pass pic_in=NULL to flush.
    /// Returns 1 if a frame was output, 0 if pipeline is filling/empty, negative on error.
    pub fn x265_encoder_encode(
        encoder: *mut x265_encoder,
        pp_nal:  *mut *mut x265_nal,
        pi_nal:  *mut u32,
        pic_in:  *mut x265_picture,
        pic_out: *mut x265_picture,
    ) -> c_int;

    /// Retrieve encoder statistics.
    pub fn x265_encoder_get_stats(
        encoder:        *mut x265_encoder,
        stats:          *mut x265_stats,
        statsSizeBytes: u32,
    );

    /// Close the encoder and release resources.
    pub fn x265_encoder_close(encoder: *mut x265_encoder);

    // ── misc ─────────────────────────────────────────────────────────────────

    /// Release library-wide static allocations.
    pub fn x265_cleanup();

    /// Library version string.
    pub static x265_version_str:    *const c_char;

    /// Build info string.
    pub static x265_build_info_str: *const c_char;

    /// Maximum bit depth this library was compiled with (8 or 10).
    pub static x265_max_bit_depth:  c_int;
}

// ─── stats (we declare only what we use) ─────────────────────────────────────

#[repr(C)]
pub struct x265_stats {
    pub globalPsnrY:           c_double,
    pub globalPsnrU:           c_double,
    pub globalPsnrV:           c_double,
    pub globalPsnr:            c_double,
    pub globalSsim:            c_double,
    pub elapsedEncodeTime:     c_double,
    pub elapsedVideoTime:      c_double,
    pub bitrate:               c_double,
    pub aggregateVmafScore:    c_double,
    pub accBits:               u64,
    pub encodedPictureCount:   u32,
    pub totalWPFrames:         u32,
    // slice stats omitted — zero-init and never read
    _pad: [u8; 512],
}

impl Default for x265_stats {
    fn default() -> Self {
        // Safety: all-zero is a valid initialised state for reading stats into
        unsafe { std::mem::zeroed() }
    }
}

// ─── error codes ─────────────────────────────────────────────────────────────

pub const X265_PARAM_BAD_NAME:  c_int = -1;
pub const X265_PARAM_BAD_VALUE: c_int = -2;

// ─── versioned encoder_open, reached via x265_api_query ───────────────────────
//
// Modern libx265 renames x265_encoder_open to x265_encoder_open_<X265_BUILD>
// via a preprocessor glue macro (see x265.h), so C callers get the right
// symbol automatically at compile time, but a hand-written extern "C"
// declaration of the bare name links against a symbol that doesn't exist
// in the compiled library. libx265 documents exactly one stable,
// unversioned entry point for exactly this situation: x265_api_query(),
// which returns a table of function pointers (including encoder_open)
// after checking ABI compatibility internally — the same mechanism x265's
// own header points external / dlopen-style consumers at.
//
// api_build_number: /* X265_BUILD (soname) */
//
// Only the fields through `encoder_open` are declared: x265_api is never
// allocated or copied by value here, only read through the `*const x265_api`
// libx265 itself returns, and nothing past encoder_open is used.
#[repr(C)]
pub struct x265_api {
    pub api_major_version: c_int,
    pub api_build_number:  c_int,
    pub sizeof_param:          c_int,
    pub sizeof_picture:        c_int,
    pub sizeof_analysis_data:  c_int,
    pub sizeof_zone:           c_int,
    pub sizeof_stats:          c_int,
    pub bit_depth:      c_int,
    pub version_str:    *const c_char,
    pub build_info_str: *const c_char,
    pub param_alloc:   Option<unsafe extern "C" fn() -> *mut x265_param>,
    pub param_free:    Option<unsafe extern "C" fn(*mut x265_param)>,
    pub param_default: Option<unsafe extern "C" fn(*mut x265_param)>,
    pub param_parse:   Option<unsafe extern "C" fn(*mut x265_param, *const c_char, *const c_char) -> c_int>,
    pub scenecut_aware_qp_param_parse:
                       Option<unsafe extern "C" fn(*mut x265_param, *const c_char, *const c_char) -> c_int>,
    pub param_apply_profile:  Option<unsafe extern "C" fn(*mut x265_param, *const c_char) -> c_int>,
    pub param_default_preset: Option<unsafe extern "C" fn(*mut x265_param, *const c_char, *const c_char) -> c_int>,
    pub picture_alloc: Option<unsafe extern "C" fn() -> *mut x265_picture>,
    pub picture_free:  Option<unsafe extern "C" fn(*mut x265_picture)>,
    pub picture_init:  Option<unsafe extern "C" fn(*mut x265_param, *mut x265_picture)>,
    pub encoder_open:  Option<unsafe extern "C" fn(*mut x265_param) -> *mut x265_encoder>,
}

#[cfg_attr(windows, link(name = "x265-static"))]
#[cfg_attr(not(windows), link(name = "x265"))]
extern "C" {
    /// Retrieve the programming interface for the linked x265 library.
    /// Stable, unversioned symbol — unlike x265_api_get/x265_encoder_open,
    /// this one is not renamed via the X265_BUILD glue macro, which is the
    /// whole point: it exists so external tools that can't run the C
    /// preprocessor over x265.h (like us) have a fixed name to link
    /// against. bitDepth=0 always returns non-NULL from the linked
    /// library. err receives one of the X265_API_QUERY_ERR_* codes.
    pub fn x265_api_query(bit_depth: c_int, api_version: c_int, err: *mut c_int) -> *const x265_api;
}

extern "C" {
    /// Build-time probe (src/x265_build_probe.c): returns X265_BUILD from
    /// whichever x265_config.h is actually being linked against.
    fn onas_x265_build_number() -> c_int;
}

pub const X265_API_QUERY_ERR_NONE:           c_int = 0;
pub const X265_API_QUERY_ERR_VER_REFUSED:    c_int = 1;
pub const X265_API_QUERY_ERR_LIB_NOT_FOUND:  c_int = 2;
pub const X265_API_QUERY_ERR_FUNC_NOT_FOUND: c_int = 3;
pub const X265_API_QUERY_ERR_WRONG_BITDEPTH: c_int = 4;

/// Open an encoder; copies all parameters. Returns NULL on failure.
///
/// Same name and signature as libx265's own `x265_encoder_open` so callers
/// use it exactly like any other function in this crate — internally it
/// goes through `x265_api_query()` to reach the real, version-suffixed
/// symbol instead of linking a name that doesn't exist in the compiled
/// library (see the comment above `x265_api` for why).
///
/// # Safety
/// `param` must be a valid pointer from `x265_param_alloc()`, as with any
/// other function in this crate.
pub unsafe fn x265_encoder_open(param: *mut x265_param) -> *mut x265_encoder {
    let build = onas_x265_build_number();
    let mut err: c_int = 0;
    let api = x265_api_query(8, build, &mut err);
    if api.is_null() {
        return std::ptr::null_mut();
    }
    match (*api).encoder_open {
        Some(f) => f(param),
        None    => std::ptr::null_mut(),
    }
}
